name = "dev-widgets"
version = "0.0.1"
defaultTargets = ["DevWidgets"]
testDriver = "Tests"

[[lean_lib]]
name = "DevWidgets"
roots = ["DevWidgets.CE", "DevWidgets.PTracker", "DevWidgets.InfoTreeExplorer", "DevWidgets.DocString", "DevWidgets.Lib"]

[[lean_lib]]
name = "Tests"
roots = [
  "tests.CE.RpcAndSchema",
  "tests.PTracker.RpcContracts",
  "tests.InfoTreeExplorer.AtPos",
  "tests.InfoTreeExplorer.RpcContracts",
  "tests.Lib.Resource",
  "tests.Rpc.QualifiedMethodNames",
  "tests.DocString.Resolver",
  "tests.DocString.VersoLean"
]
